name: IceBoatRace
version: '1.0-SNAPSHOT'
main: org.limelight.iceBoatRace.IceBoatRace
api-version: '1.21'
commands:
  startvote:
    description: starts the voting process for next map
    usage: /<command>
  endvote:
    description: ends the voting process for next map
    usage: /<command>
  iceboat_debug:
    description: used to debug sections of the IceBoatRace plugin
    usage: /<command> <argument>

