name: IceBoatRace
version: '1.0-SNAPSHOT'
main: org.limelight.iceBoatRace.IceBoatRace
api-version: '1.21'
commands:
  votestart:
    description: starts the voting process for next map
    usage: /<command>
  voteend:
    description: ends the voting process for next map
    usage: /<command>
  iceboat_debug:
    description: used to debug sections of the IceBoatRace plugin
    usage: /<command> <argument>
  scb:
    description: spawns a custom boat
    usage: /<command>

